### ISSUE TITLE
Overview: changes before merging dev into master

### ISSUE THREAD

**Issue by drvdputt** [PAHFIT/pahfit#246]
Making a list of important and/or small things that need to change before we merge the dev branch into master.

- [x] Merge tabulate function pull request (#249 also contains important discussion points and some tweaks I have to do)  
- [X] Inform user better about instrument packs: #245 (marked as done, but should write a sentence in the documentation. The demo notebook also shows how to get a list of instruments)
- [X] Make sure all example data work in terms of instrument bounds and data loading: #239 and #244 (the loading issues have been solved. ISO pack still needs a tweak) 
- [ ] **Optional** Some info about example spectra in the readme of that directory: #243 
- [ ] **Optional** merge in new guess function: #242 
- [ ] **Optional** make sure plotting code works with AND without attenuation: code from my personal dev branch
- [ ] **After merge is fine too** Cleaning up documentation: #247

**Comment by BethanyRS** [comment]
Regarding the "cleaning up documentation" point, I just added issue #247. Although, it's more like a list of suggestions than an actual issue.

**Comment by drvdputt** [comment]
I have added the "tabulate" pull request to this. Important for the dev branch merge, because it prevents leaking the underlying fitting objects, and it also contains some small conceptual changes.

**Comment by jdtsmith** [comment]
Since v2.5 was released already quite a while back I'm closing this.  Please open as new issues any optional issues that remain.
